package org.solvik.transpiler;

public enum TokenKind {
    EOF, NEWLINE, IDENT, INT, REAL, STRING, CHAR,
    PACKAGE, USE, STRUCT, TRAIT, ENUM, EXTENDS, IMPLEMENTS, SELF_TYPE, SELF,
    PUBLIC, FUNC, DELEGATE, TO, STATIC, MUTABLE, MATCH, IF, ELSE, LET, WHILE, FOR,
    IN, SWITCH, CASE, DEFAULT, TRY, CATCH, FINALLY, THROW, RETURN, BREAK, CONTINUE,
    TRUE, FALSE, NULL, IS,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, LT, GT, COMMA, DOT, QUESTION_MARK,
    RANGE, RANGE_INCLUSIVE, SPREAD, COLON, SEMICOLON, ASSIGN, EQ, NE, LE, GE,
    BANG, PLUS, MINUS, STAR, SLASH, PERCENT, AMPERSAND, PLUS_ASSIGN, MINUS_ASSIGN,
    STAR_ASSIGN, SLASH_ASSIGN, PERCENT_ASSIGN, COALESCE, AND, OR, ARROW
}
