package org.solvik.transpiler.backend;

import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;

import org.solvik.transpiler.SolvikIr;
import org.solvik.transpiler.SolvikProgram;
import org.solvik.transpiler.SolvikStmt;
import org.solvik.transpiler.TypeModel.Base;
import org.solvik.transpiler.TypeModel.Type;

import static org.solvik.transpiler.TypeModel.*;
import org.solvik.transpiler.language.Literals;

import static org.solvik.transpiler.language.Language.*;

/**
 * Renders the Java backend IR to deterministic Java 17 source.
 *
 * <p>The emitter is intentionally boring: it walks the lowered program, writes
 * Java syntax, manages indentation, and delegates every representation decision
 * to {@link JavaLowerer}. It does not inspect the parser AST, resolve names,
 * infer or promote types, or choose runtime helpers.</p>
 */
public final class JavaEmitter {
    private final JavaProgram program;
    private final JavaLowerer lowerer;
    private final StringBuilder out = new StringBuilder();
    private StringBuilder sink = out;
    private String indentPad = "";
    private boolean emittingStaticBlock;
    private int temp;

    public JavaEmitter(JavaProgram program) {
        this.program = program;
        this.lowerer = new JavaLowerer(program);
    }

    public JavaLowerer lowerer() { return lowerer; }

    public String emit() {
        SolvikProgram solvik = program.program();
        StringBuilder declarations = new StringBuilder();
        sink = declarations;
        for (SolvikProgram.Trait trait : solvik.traits()) emitTrait(trait);
        for (SolvikProgram.Enum enumeration : solvik.enums()) emitEnum(enumeration);
        for (SolvikProgram.Struct struct : solvik.structs()) emitStruct(struct);
        emitMain();
        sink = out;
        EnumSet<RuntimeFeature> features = program.features();
        line("// Generated by the Solvik Java 17 transpiler.");
        line("// Source: " + program.sourceName().replace("\\", "/"));
        line("// Do not edit by hand.");
        emitImports(features);
        line("public final class " + program.outputClass() + " {");
        indent();
        emitRuntime(features);
        out.append(declarations);
        outdent();
        line("}");
        return out.toString();
    }

    private void emitImports(EnumSet<RuntimeFeature> features) {
        line("import java.io.*;");
        line("import java.math.*;");
        line("import java.nio.charset.StandardCharsets;");
        line("import java.util.*;");
        if (features.contains(RuntimeFeature.FILE)) line("import java.nio.file.*;");
        if (features.contains(RuntimeFeature.HASH)) line("import java.security.*;");
        if (features.contains(RuntimeFeature.REGEX)) line("import java.util.regex.*;");
        if (features.contains(RuntimeFeature.REGEX) || features.contains(RuntimeFeature.PROPERTIES) || features.contains(RuntimeFeature.SEMAPHORE)) line("import java.util.concurrent.*;");
        if (features.contains(RuntimeFeature.MUTEX)) line("import java.util.concurrent.locks.*;");
    }



























    private void emitTrait(SolvikProgram.Trait declaration) {
        line("public interface " + program.traitName(declaration.name()) + typeParametersIr(declaration.typeParameters()) + extendsTraitsIr(declaration.extendsTypes()) + " {"); indent();
        for (SolvikProgram.Method method : declaration.methods()) {
            line("@SuppressWarnings(\"finally\")");
            String signature = "public " + (method.body() == null ? "" : "default ") + methodTypeParametersIr(method) + lowerer.javaType(method.returnType(), method.returnBoxed()) + " " + lowerer.methodName(method.name()) + "(" + parametersIr(method.params()) + ")";
            if (method.body() == null) line(signature + ";");
            else { line(signature + " {"); indent(); for (SolvikStmt s : method.body()) emitStmt(s); outdent(); line("}"); }
        }
        outdent(); line("}");
    }

    private String extendsTraitsIr(List<Type> refs) {
        if (refs.isEmpty()) return "";
        StringBuilder s = new StringBuilder(" extends ");
        for (int i = 0; i < refs.size(); i++) { if (i > 0) s.append(", "); s.append(lowerer.javaType(refs.get(i))); }
        return s.toString();
    }

    private void emitEnum(SolvikProgram.Enum declaration) {
        String n = program.enumName(declaration.name());
        line("public static final class " + n + typeParametersIr(declaration.typeParameters()) + " {"); indent();
        line("private final int tag; private final Object payload;");
        line("private " + n + "(int tag,Object payload){this.tag=tag;this.payload=payload;}");
        for (int i = 0; i < declaration.variants().size(); i++) {
            SolvikProgram.Variant v = declaration.variants().get(i);
            if (v.payload() == null) line("@SuppressWarnings(\"rawtypes\") public static final " + n + " " + v.name() + " = new " + n + "(" + i + ", null);");
            else line("public static " + (declaration.typeParameters().isEmpty() ? "" : typeParametersIr(declaration.typeParameters()) + " ") + n + typeArgumentsIr(declaration.typeParameters()) + " " + v.name() + "(" + lowerer.javaType(v.payload()) + " value){return new " + n + typeArgumentsIr(declaration.typeParameters()) + "(" + i + ",value);}");
        }
        line("int tag(){return tag;} Object payload(){return payload;}");
        line("@Override public boolean equals(Object o){return o instanceof " + n + (declaration.typeParameters().isEmpty() ? "" : "<?>") + " x && tag==x.tag && RT.eq(payload,x.payload);}");
        line("@Override public int hashCode(){return 31*tag+Objects.hashCode(payload);}");
        line("@Override public String toString(){return payload==null?Integer.toString(tag):Integer.toString(tag)+\"(\"+RT.format(payload)+\")\";}");
        outdent(); line("}");
    }

    private void emitStruct(SolvikProgram.Struct declaration) {
        StringBuilder header = new StringBuilder("public static final class ").append(program.structName(declaration.name())).append(typeParametersIr(declaration.typeParameters()));
        List<String> bases = new ArrayList<>();
        for (Type t : declaration.implementsTypes()) { if (t.base() == Base.RUNNABLE) bases.add("RT.RunnableLike"); else bases.add(lowerer.javaType(t)); }
        if (!bases.isEmpty()) header.append(" implements ").append(String.join(", ", bases));
        line(header + " {"); indent();
        for (SolvikProgram.Field field : declaration.fields()) {
            String modifier = field.isStatic() ? "private static " : field.isVar() ? "private " : "private final ";
            line(modifier + lowerer.javaType(field.type()) + " " + lowerer.fieldName(field.name()) + (field.initializer() == null ? ";" : " = " + lowerer.emit(field.initializer()) + ";"));
        }
        List<SolvikProgram.Field> instanceFields = new ArrayList<>();
        for (SolvikProgram.Field f : declaration.fields()) if (!f.isStatic()) instanceFields.add(f);
        StringBuilder constructorParameters = new StringBuilder();
        for (int i = 0; i < instanceFields.size(); i++) { if (i > 0) constructorParameters.append(", "); SolvikProgram.Field f = instanceFields.get(i); constructorParameters.append(lowerer.javaType(f.type())).append(' ').append(lowerer.fieldName(f.name())); }
        line("private " + program.structName(declaration.name()) + "(" + constructorParameters + ") {"); indent();
        for (SolvikProgram.Field f : instanceFields) line("this." + lowerer.fieldName(f.name()) + " = " + lowerer.fieldName(f.name()) + ";");
        outdent(); line("}");
        line(String.format("@Override public String toString(){return \"<instance #%d>\";}", declaration.index()));
        if (declaration.staticBlock() != null) { line("static {"); indent(); boolean previous = emittingStaticBlock; emittingStaticBlock = true; for (SolvikStmt s : declaration.staticBlock()) emitStmt(s); emittingStaticBlock = previous; outdent(); line("}"); }
        for (SolvikProgram.Method method : declaration.methods()) {
            // A trivial `new` factory (a pure field permutation of its parameters) has
            // every call site lowered straight to the generated all-fields constructor,
            // so the synthetic `__new` forwarding method would be dead code; omit it.
            if (isTrivialFactory(declaration.name(), method)) continue;
            emitMethod(method);
        }
        outdent(); line("}");
    }

    private boolean isTrivialFactory(String structName, SolvikProgram.Method method) {
        return method.name().equals("new") && !method.instance() && program.trivialFactory(structName) != null;
    }

    private void emitMethod(SolvikProgram.Method method) {
        String access = method.isPub() ? "public " : "private ";
        if (!method.instance()) access += "static ";
        line("@SuppressWarnings(\"finally\")");
        line(access + methodTypeParametersIr(method) + lowerer.javaType(method.returnType(), method.returnBoxed()) + " " + lowerer.methodName(method.name()) + "(" + parametersIr(method.params()) + ") {"); indent();
        if (method.body() != null) for (SolvikStmt s : method.body()) emitStmt(s);
        outdent(); line("}");
    }

    private String typeParametersIr(List<SolvikProgram.TypeParameter> params) {
        if (params.isEmpty()) return "";
        return "<" + params.stream().map(p -> {
            String bounds = p.bounds().stream().map(lowerer::javaType).reduce((a,b)->a+" & "+b).orElse("");
            return p.name() + (bounds.isEmpty() ? "" : " extends " + bounds);
        }).reduce((a,b)->a+", "+b).orElse("") + ">";
    }

    private String methodTypeParametersIr(SolvikProgram.Method method) {
        return method.typeParameters().isEmpty() ? "" : typeParametersIr(method.typeParameters()) + " ";
    }

    private String typeArgumentsIr(List<SolvikProgram.TypeParameter> params) { return params.isEmpty() ? "" : "<" + params.stream().map(SolvikProgram.TypeParameter::name).reduce((a,b)->a+", "+b).orElse("") + ">"; }

    private String parametersIr(List<SolvikProgram.Parameter> params) {
        if (params.isEmpty()) return "";
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) result.append(", ");
            SolvikProgram.Parameter p = params.get(i);
            if (p.variadic()) program.require(RuntimeFeature.LIST);
            result.append(p.variadic() ? "RT.SList<" + lowerer.javaType(p.type(), true) + ">" : lowerer.javaType(p.type(), p.boxed())).append(' ').append(lowerer.localName(p.name()));
        }
        return result.toString();
    }

    private void emitMain() {
        program.require(RuntimeFeature.LIST);
        line("public static void main(String[] args) {"); indent();
        line("try {"); indent();
        line("int __exit = " + program.structName("Main") + ".run(RT.strings(args));");
        line("System.exit(__exit);");
        outdent(); line("} catch (RT.Thrown __t) {"); indent();
        line("System.err.println(\"runtime error: \" + RT.format(__t.value));"); line("System.exit(2);");
        outdent(); line("} catch (ExceptionInInitializerError __t) {"); indent();
        line("Throwable __cause = __t.getCause(); if (__cause instanceof RT.Thrown __rt) System.err.println(\"runtime error: \" + RT.format(__rt.value)); else System.err.println(\"runtime error: \" + (__cause == null ? __t.toString() : __cause.getMessage()));"); line("System.exit(2);");
        outdent(); line("} catch (RuntimeException __t) {"); indent();
        line("System.err.println(\"runtime error: \" + __t.getMessage());"); line("System.exit(2);");
        outdent(); line("}"); outdent(); line("}");
    }

    private void emitStmt(SolvikStmt statement) {
        if (statement instanceof SolvikStmt.VarDecl d) {
            // A match used as a value is lowered to an if/else chain that assigns
            // the result, avoiding an allocating Supplier lambda per evaluation.
            if (d.initializer() instanceof SolvikIr.Match m) { line(lowerer.javaType(d.type()) + " " + lowerer.localName(d.name()) + ";"); emitMatchHoisted(m, lowerer.localName(d.name()), false); return; }
            line(lowerer.javaType(d.type()) + " " + lowerer.localName(d.name()) + (d.initializer() == null ? ";" : " = " + lowerer.emit(d.initializer()) + ";"));
        }
        else if (statement instanceof SolvikStmt.Expr e) {
            if (e.expression() instanceof SolvikIr.Assign a && a.value() instanceof SolvikIr.Match m && hoistableMatchTarget(a.target())) { emitMatchHoisted(m, lowerer.emit(a.target()), false); return; }
            line(lowerer.emit(e.expression()) + ";");
        }
        else if (statement instanceof SolvikStmt.Return r) {
            if (r.value() instanceof SolvikIr.Match m) { emitMatchHoisted(m, null, true); return; }
            line(r.value() == null ? "return;" : "return " + lowerer.emit(r.value()) + ";");
        }
        else if (statement instanceof SolvikStmt.If i) { line("if (" + lowerer.emit(i.condition()) + ") {"); indent(); for (SolvikStmt s : i.thenBranch()) emitStmt(s); outdent(); line("}"); if (!i.elseBranch().isEmpty()) { line("else {"); indent(); for (SolvikStmt s : i.elseBranch()) emitStmt(s); outdent(); line("}"); } }
        else if (statement instanceof SolvikStmt.While w) { line("while (" + lowerer.emit(w.condition()) + ") {"); indent(); for (SolvikStmt s : w.body()) emitStmt(s); outdent(); line("}"); }
        else if (statement instanceof SolvikStmt.ForRange f) { String cmp = f.inclusive() ? " <= " : " < "; line("for (" + lowerer.javaType(f.loopType()) + " " + lowerer.localName(f.name()) + " = " + lowerer.emit(f.start()) + "; " + lowerer.localName(f.name()) + cmp + lowerer.emit(f.end()) + "; " + lowerer.localName(f.name()) + "++) {"); indent(); for (SolvikStmt s : f.body()) emitStmt(s); outdent(); line("}"); }
        else if (statement instanceof SolvikStmt.ForEach f) { boolean stringIteration = f.iterable().type() != null && f.iterable().type().base() == Base.STRING; if (stringIteration) program.require(RuntimeFeature.STRING_ITER); String expression = stringIteration ? "RT.codePoints(" + lowerer.emit(f.iterable()) + ")" : lowerer.emit(f.iterable()); line("for (" + lowerer.javaType(f.elementType(), true) + " " + lowerer.localName(f.name()) + " : " + expression + ") {"); indent(); for (SolvikStmt s : f.body()) emitStmt(s); outdent(); line("}"); }
        else if (statement instanceof SolvikStmt.Switch s) {
            List<List<Long>> constantCases = lowerer.constantIntegerCases(s);
            if (constantCases != null) { emitJavaSwitch(s, constantCases); return; }
            String subject = "__switch" + temp++; line((s.directEquality() ? lowerer.javaType(s.subjectType()) : "Object") + " " + subject + " = " + lowerer.emit(s.subject()) + ";"); boolean first = true; for (SolvikStmt.SwitchCase c : s.cases()) { String condition = c.isDefault() ? "true" : c.values().stream().map(v -> s.directEquality() ? lowerer.switchEquality(subject, s.subjectType(), v) : "RT.eq(" + subject + ", " + lowerer.emit(v) + ")").reduce((a,b)->a+" || "+b).orElse("false"); line(!first && condition.equals("true") ? "else {" : (first ? "if" : "else if") + " (" + JavaLowerer.unparenthesize(condition) + ") {"); indent(); for (SolvikStmt st : c.body()) emitStmt(st); outdent(); line("}"); first = false; } }
        else if (statement instanceof SolvikStmt.Try t) { line("try {"); indent(); for (SolvikStmt st : t.body()) emitStmt(st); outdent(); line("}"); if (!t.catches().isEmpty()) { line("catch (RT.Thrown __caught) {"); indent(); for (int i = 0; i < t.catches().size(); i++) { SolvikStmt.Catch c = t.catches().get(i); String type = lowerer.javaType(c.type()); String condition = c.type().base() == Base.THROWABLE ? "true" : "__caught.value instanceof " + type; line((i == 0 ? "if" : "else if") + " (" + condition + ") {"); indent(); line(type + " " + lowerer.localName(c.name()) + " = " + (type.equals("Object") ? "__caught.value" : "(" + type + ") __caught.value") + ";"); for (SolvikStmt st : c.body()) emitStmt(st); outdent(); line("}"); } line("else throw __caught;"); outdent(); line("}"); } if (t.finallyBlock() != null) { line("finally {"); indent(); for (SolvikStmt st : t.finallyBlock()) emitStmt(st); outdent(); line("}"); } }
        else if (statement instanceof SolvikStmt.Throw t) line((emittingStaticBlock ? "if (RT.always()) " : "") + "throw new RT.Thrown(" + lowerer.emit(t.value()) + ");");
        else if (statement instanceof SolvikStmt.Break) line("break;");
        else if (statement instanceof SolvikStmt.Continue) line("continue;");
        else if (statement instanceof SolvikStmt.Block b) { line("{"); indent(); for (SolvikStmt s : b.statements()) emitStmt(s); outdent(); line("}"); }
        else if (statement instanceof SolvikStmt.MatchStmt m) emitMatchStmt(m);
    }



    private void emitJavaSwitch(SolvikStmt.Switch s, List<List<Long>> constantCases) {
        String subject = "__switch" + temp++;
        line(lowerer.javaType(s.subjectType()) + " " + subject + " = " + lowerer.emit(s.subject()) + ";");
        line("switch (" + subject + ") {"); indent();
        for (int i = 0; i < s.cases().size(); i++) {
            SolvikStmt.SwitchCase c = s.cases().get(i);
            if (c.isDefault()) line("default:");
            else for (Long value : constantCases.get(i)) line("case " + value + ":");
            indent();
            for (SolvikStmt st : c.body()) emitStmt(st);
            if (!lowerer.blockDiverges(c.body())) line("break;");
            outdent();
        }
        outdent(); line("}");
    }




    private void emitMatchStmt(SolvikStmt.MatchStmt match) {
        Type subjectType = match.subject().type(); String subject = "__match" + temp++; boolean typed = lowerer.matchSubjectJavaType(subjectType) != null;
        line((typed ? lowerer.matchSubjectJavaType(subjectType) : "Object") + " " + subject + " = " + lowerer.emit(match.subject()) + ";");
        boolean first = true;
        for (SolvikIr.MatchArm arm : match.arms()) {
            String condition = lowerer.javaPatternCondition(arm.pattern(), subject, subjectType, typed);
            if (condition.equals("true")) line(first ? "{" : "else {");
            else line((first ? "if" : "else if") + " (" + JavaLowerer.unparenthesize(condition) + ") {");
            indent();
            for (String declaration : lowerer.javaPatternBindings(arm.pattern(), subject, subjectType, typed)) line(declaration);
            line(lowerer.emit(arm.body()) + ";");
            outdent(); line("}");
            first = false;
        }
    }

    private void emitMatchHoisted(SolvikIr.Match match, String target, boolean returnMode) {
        Type subjectType = match.subject().type();
        if (match.arms().isEmpty()) {
            line("throw new RT.Thrown(new RT.ExceptionValue(\"non-exhaustive match\"));");
            return;
        }
        boolean typed = lowerer.matchSubjectJavaType(subjectType) != null;
        String subject = "__match" + temp++;
        line((typed ? lowerer.matchSubjectJavaType(subjectType) : "Object") + " " + subject + " = " + lowerer.emit(match.subject()) + ";");
        boolean first = true; boolean exhaustive = false;
        for (SolvikIr.MatchArm arm : match.arms()) {
            String condition = lowerer.javaPatternCondition(arm.pattern(), subject, subjectType, typed);
            if (condition.equals("true")) { line(first ? "{" : "else {"); exhaustive = true; }
            else line((first ? "if" : "else if") + " (" + JavaLowerer.unparenthesize(condition) + ") {");
            indent();
            for (String declaration : lowerer.javaPatternBindings(arm.pattern(), subject, subjectType, typed)) line(declaration);
            line((returnMode ? "return " : target + " = ") + lowerer.emit(arm.body()) + ";");
            outdent(); line("}");
            first = false;
            if (exhaustive) break;
        }
        if (!exhaustive) {
            if (returnMode) {
                line("throw new RT.Thrown(new RT.ExceptionValue(\"non-exhaustive match\"));");
            } else {
                line("else {"); indent();
                line("throw new RT.Thrown(new RT.ExceptionValue(\"non-exhaustive match\"));");
                outdent(); line("}");
            }
        }
    }

    private boolean hoistableMatchTarget(SolvikIr target) {
        return target instanceof SolvikIr.Local || target instanceof SolvikIr.Field;
    }

    private void line(String text) { sink.append(indentPad).append(text).append('\n'); }

    private void indent() { indentPad += "    "; }

    private void outdent() { indentPad = indentPad.substring(0, indentPad.length() - 4); }

    private void emitRuntime(EnumSet<RuntimeFeature> features) {
        new JavaRuntime().emit(new JavaRuntime.RuntimeSink() {
            @Override public void line(String text) { JavaEmitter.this.line(text); }
            @Override public void indent() { JavaEmitter.this.indent(); }
            @Override public void outdent() { JavaEmitter.this.outdent(); }
        }, features);
    }

}
